export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const CHANGE_STATUS_TODO = 'CHANGE_STATUS_TODO'
export const GET_ALL_TODOS = 'GET_ALL_TODOS'
export const EDIT_TODOS = 'EDIT_TODOS'
